exclude: |
    (?x)^(
        {{cookiecutter.package_name}}/tests/test_import.py
    )$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=25']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-vcs-permalinks
    -   id: check-yaml
        exclude:  |
            (?x)^(
                {{cookiecutter.package_name}}/environment.yml|
                {{cookiecutter.package_name}}/.pre-commit-config.yaml
            )$
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: text-unicode-replacement-char
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
    -   id: setup-cfg-fmt
        exclude:  |
            (?x)^(
                {{cookiecutter.package_name}}/setup.cfg
            )$
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [hooks, tests]
        pass_filenames: false
-   repo: https://github.com/dosisod/refurb
    rev: v2.0.0
    hooks:
    -   id: refurb
        args: [--ignore, FURB126]
        exclude: ({{cookiecutter.package_name}})
-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
    -   id: interrogate
        args: [-v, --fail-under=40]
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.18
    hooks:
    -   id: mdformat
        additional_dependencies: [
            mdformat-gfm,
            mdformat-black,
        ]
        args: [--wrap, "88"]
        files: (README\.md)
        exclude: |
          (?x)^(
              {{cookiecutter.package_name}}/README.md
          )$
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.18
    hooks:
    -   id: mdformat
        additional_dependencies: [
            mdformat-myst,
            mdformat-black,
        ]
        args: [--wrap, "88"]
        files: (docs/.)
        # Exclude files with admonitions.
        # exclude: |
        #     (?x)^(
        #         path/to/file.py
        #     )$
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
        additional_dependencies: [tomli]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.12.1'
    hooks:
    -   id: mypy
        args: [
            --no-strict-optional,
            --ignore-missing-imports,
        ]
        pass_filenames: false
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
    # -   id: identity  # Prints all files passed to pre-commits. Debugging.
