exclude: |
    (?x)^(
        {{cookiecutter.package_name}}/tests/test_import.py
    )$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=25']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-vcs-permalinks
    -   id: check-yaml
        exclude:  |
            (?x)^(
                {{cookiecutter.package_name}}/.pre-commit-config.yaml
            )$
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: text-unicode-replacement-char
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v3.2.0
    hooks:
    -   id: setup-cfg-fmt
        exclude:  |
            (?x)^(
                {{cookiecutter.package_name}}/setup.cfg
            )$
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
    -   id: ruff-check
        args: [--fix, hooks, tests]
        pass_filenames: false
    -   id: ruff-format
        args: [hooks, tests]
        pass_filenames: false
-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
    -   id: interrogate
        args: [-v, --fail-under=40]
-   repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
    -   id: mdformat
        additional_dependencies: [mdformat-gfm]
        args: [--wrap, "88"]
        files: (README\.md)
        exclude: |
          (?x)^(
              {{cookiecutter.package_name}}/README.md
          )$
-   repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
    -   id: mdformat
        additional_dependencies: [mdformat-myst]
        args: [--wrap, "88"]
        files: (docs/.)
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
    -   id: codespell
        additional_dependencies: [tomli]
        exclude: (^|/)uv\.lock$
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
