name: cpp

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.7
  - pip
  - setuptools_scm
  - toml

  # Package dependencies
  - cookiecutter >=2.1.0
  - pytask >=0.2

  # Misc
  - black
  - mypy
  - pre-commit
  - pytest
  # - pytest-cookies>=0.6.2
  - pytest-cov
  - pytest-xdist
  - tox-conda

  # Documentation
  - furo
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-panels

  - pip:
    - git+https://github.com/andriihomiak/pytest-cookies.git@fix/quotes_in_user_config
