name: main

# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CONDA_EXE: mamba

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'

jobs:

  run-tests:

    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,nodefaults
          miniforge-variant: Mambaforge

      - name: Install core dependencies.
        shell: bash -l {0}
        run: mamba install -c conda-forge tox-conda coverage

      # Unit, integration, and end-to-end tests.

      - name: Run unit tests and doctests.
        shell: bash -l {0}
        run: tox -e pytest -- -m "unit or (not integration and not end_to_end)" --cov=./ --cov-report=xml -n auto

      - name: Upload coverage report for unit tests and doctests.
        if: runner.os == 'Linux' && matrix.python-version == '3.9'
        shell: bash -l {0}
        run: bash <(curl -s https://codecov.io/bash) -F unit -c

      - name: Run end-to-end tests.
        shell: bash -l {0}
        run: tox -e pytest -- -m end_to_end --cov=./ --cov-report=xml -n auto

      - name: Upload coverage reports of end-to-end tests.
        if: runner.os == 'Linux' && matrix.python-version == '3.9'
        shell: bash -l {0}
        run: bash <(curl -s https://codecov.io/bash) -F end_to_end -c


  docs:

    name: Run documentation.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false
          environment-name: gha-docs
          channels: conda-forge,nodefaults
          extra-specs: |
            python=3.11
            mamba
            tox-conda
          cache-downloads: true

      - name: Build docs
        shell: bash -l {0}
        run: tox -e sphinx
