name: {{ cookiecutter.conda_environment_name }}

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip
  - setuptools_scm
  - toml

  # Package dependencies
  - pytask >=0.2
  - pytask-parallel >=0.2

  # Misc
  - black
  - jupyterlab
  - pre-commit
  - pytest-cov
  - pytest-xdist
  - tox-conda
